# Generated by Django 3.2 on 2024-02-27 15:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_description', models.TextField()),
                ('room_availability', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('S', 'Single'), ('SH', 'Shared')], max_length=2)),
                ('room_photos', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('room_location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
