# Generated by Django 3.2 on 2024-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_photos',
        ),
    ]
