# Generated by Django 3.2 on 2024-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(default='default@example.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='owner_phone',
            field=models.CharField(default='+1234567890', max_length=20),
            preserve_default=False,
        ),
    ]
