# Generated by Django 3.2 on 2024-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20240304_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_pending_approval',
            field=models.BooleanField(default=True),
        ),
    ]
