# Generated by Django 4.2.11 on 2024-03-16 13:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room_is_pending_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
