# Generated by Django 4.2.11 on 2024-03-20 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_location',
            field=models.CharField(max_length=20),
        ),
    ]
