# Generated by Django 4.2.11 on 2024-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_room_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(max_length=200),
        ),
    ]
